//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobMon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\graha\\Documents\\")]
        public string WorkingFolder {
            get {
                return ((string)(this["WorkingFolder"]));
            }
            set {
                this["WorkingFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://www.jobsite.co.uk/cgi-bin/advsearch?rss_feed=1&amp;daysback=1&amp;jbe_id=33076029</string>
  <string>http://www.jobsite.co.uk/cgi-bin/advsearch?rss_feed=1&amp;daysback=1&amp;jbe_id=43459304</string>
  <string>http://www.jobsite.co.uk/cgi-bin/advsearch?rss_feed=1&amp;daysback=1&amp;jbe_id=47879865</string>
  <string>http://www.jobserve.com/MySearch/F28DE6D13D1400.rss</string>
  <string>http://www.jobserve.com/MySearch/1B9BB1BE02F6D5.rss</string>
  <string>http://www.jobserve.com/MySearch/D9C2DABB1CC76A9B.rss</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RssFeeds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RssFeeds"]));
            }
            set {
                this["RssFeeds"] = value;
            }
        }
    }
}
